info:
  app:
    name: CredHub

security:
  oauth2:
    resource:
      id: credhub
  basic:
    enabled: false
  authorization:
    acls:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate
